baseURL = "https://biyori-sh.github.io/"
languageCode = "utf-8"
title = "biyori-sh's page"
theme = "archie"
publishDir = "docs" # Directory where htmls are gerenated
# canonifyurls = true # Baseurl(root)

##### Code Highlight #####
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate = 3 # articles per page

[params]
	mode = "auto" # color-mode → light,dark or auto
	useCDN = false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "ノートなどをぼちぼち"

##### Main menu Items #####
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/post"
weight = 2

[[menu.main]]
name = "Notes"
url = "/note/note/"
weight = 3

[[menu.main]]
name = "About"
url = "/about/about/"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

##### Social Tags #####
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/biyori-sh"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/biyori_sh/"

# [[params.social]]
# name = "GitLab"
# icon = "gitlab"
# url = "https://gitlab.com/athul/"
